#ifndef SLIM_DEBUG_DEBUG_MODES_H_
# define SLIM_DEBUG_DEBUG_MODES_H_

# if _DEBUG
#  define SLIM_DEBUG_DEFAULT_MODE	1
# else
#  define SLIM_DEBUG_DEFAULT_MODE	0
# endif

# ifndef SLIM_DEBUG_DEBUG_MODE
#  define SLIM_DEBUG_DEBUG_MODE		SLIM_DEBUG_DEFAULT_MODE
# endif // !SLIM_DEBUG_DEBUG_MODE

# ifndef SLIM_DEBUG_MEMORY_MODE
#  define SLIM_DEBUG_MEMORY_MODE	SLIM_DEBUG_DEFAULT_MODE
# endif // !SLIM_DEBUG_MEMORY_MODE

#endif /* !SLIM_DEBUG_DEBUG_MODES_H_ */
