#ifndef SLIM_MEMORY_UNITS_H_
# define SLIM_MEMORY_UNITS_H_

# define SLIM_MEMORY_KILOBYTE	1000
# define SLIM_MEMORY_MEGABYTE	1000 * SLIM_MEMORY_KILOBYTE
# define SLIM_MEMORY_GIGABYTE	1000 * SLIM_MEMORY_MEGABYTE
# define SLIM_MEMORY_TERABYTE	1000 * SLIM_MEMORY_GIGABYTE

# define SLIM_MEMORY_KIBIBYTE	0x400
# define SLIM_MEMORY_MEBIBYTE	0x400 * SLIM_MEMORY_KIBIBYTE
# define SLIM_MEMORY_GIBIBYTE	0x400 * SLIM_MEMORY_MEBIBYTE
# define SLIM_MEMORY_TEBIBYTE	0x400 * SLIM_MEMORY_GIBIBYTE

#endif /* !SLIM_MEMORY_UNITS_H_ */
